# ========================
# DATABASE CONNECTION
# ========================
# tells Spring where your PostgreSQL is running
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanagement

# the username and password you set during PostgreSQL install
spring.datasource.username=postgres
spring.datasource.password=8880

# the driver class Spring uses to talk to PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / HIBERNATE
# ========================
# hibernate is the JPA implementation Spring Boot uses under the hood.
# "update" means: on startup, look at your @Entity classes and
# automatically CREATE or ALTER tables to match. Never drops existing data.
# In production you'd use "validate" or Flyway migrations instead.
spring.jpa.hibernate.ddl-auto=update

# prints every SQL statement Hibernate runs to your console.
# invaluable for learning — you can see exactly what JPA does behind the scenes.
# turn this off in production.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ========================
# APPLICATION
# ========================
spring.application.name=taskmanager
server.port=8081

# JWT SECRET KEY — used to sign and verify tokens
# in production this must be a long random string stored in environment variables
# never hardcode this in real applications
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
# 86400000 milliseconds = 24 hours